name: Build and Release to GH releases

on:
  push:
    branches: ['main']
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build using xcodebuild command
    runs-on: macos-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: xcodebuild -scheme notepaxx -configuration Release -derivedDataPath build
      - name: Extract app into a folder
        run: |
          mkdir app
          mv build/Build/Products/Release/notepaxx.app app
      - name: Codesign executable
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          SECURITY_IDENTITY: ${{ secrets.SECURITY_IDENTITY }}
        run: |
          KEYCHAIN_PASS=Password123
          echo passw ${{ secrets.MACOS_CERTIFICATE_PWD }}
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p $KEYCHAIN_PASS build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p $KEYCHAIN_PASS build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k Password123 build.keychain
          /usr/bin/codesign --force -s $SECURITY_IDENTITY ./app/notepaxx.app -v
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: notepaxxapp
          path: app/

  release-app:
    name: Release App
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download site content
        uses: actions/download-artifact@v3
        with:
          name: notepaxxapp
      - name: Zip up app Artifact
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'app.zip'
      - name: Create GH release
        id: creates_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.${{ github.run_number }}
          release_name: v1.${{ github.run_number }}.0
      - name: Upload release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.creates_release.outputs.upload_url }}
          asset_path: ./app.zip
          asset_name: notepaxxapp-v1.${{ github.run_number }}.0.zip
          asset_content_type: application/zip
